[package]
name = "tls-test"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.85.1"
build = "build.rs"

[[bin]]
name = "tls-test"
path = "src/main.rs"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
anyhow = "1"
config-portal = { path = "../common/lib/config-portal" }
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
libcrux-ml-kem = { version = "0.0.8", default-features = false, features = ["mlkem768", "std"] }
rustls = { version = "0.23", default-features = false, features = ["std", "logging", "tls12"] }
rustls-rustcrypto = "0.0.2-alpha"
webpki-roots = "1"
wifi = { path = "../common/lib/wifi" }
x25519-dalek = { version = "2", default-features = false, features = ["static_secrets"] }

[build-dependencies]
embuild = "0.33.1"
