[package]
name = "tft-display"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "=1.0.102"
embassy-time = { version = "=0.5.0", optional = true }

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-hal = "=0.46.2"
esp-idf-svc = "=0.52.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }

[features]
default = ["espidf"]
espidf = ["dep:embassy-time"]
